address: 0.0.0.0:8080
db:
  host: 0.0.0.0
  username: admin
  password: 2w3e$R%T
  database: server
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 100
  log-level: 2
es:
  servers: 127.0.0.1:9200
